"""Render `docs/implementation/roadmap.md` from the derived roadmap model."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NUMBERS = Path(__file__).resolve().parent / "issue_numbers.json"
REPO_URL = "https://github.com/Ihebdhouibi/Lexpert"


Numbers = dict[str, dict[str, object]]


def load_numbers() -> Numbers:
    """Task id to its GitHub issue number and open/closed state.

    Committed rather than fetched, so generating the roadmap needs no network and the
    pre-commit staleness hook stays deterministic. `python scripts/sync_issues.py`
    refreshes it.
    """
    if not NUMBERS.exists():
        return {}
    with NUMBERS.open(encoding="utf-8") as handle:
        raw = json.load(handle)
    out: Numbers = {}
    for key, value in raw.items():
        # Tolerate the older flat `{"FND-01": 2}` shape so a stale file still renders.
        if isinstance(value, dict):
            out[key] = {"number": int(value["number"]), "open": bool(value.get("open", True))}
        else:
            out[key] = {"number": int(value), "open": True}
    return out


def link(task_id: str, numbers: Numbers) -> str:
    entry = numbers.get(task_id)
    if entry is None:
        return f"`{task_id}`"
    label = f"[`{task_id}`]({REPO_URL}/issues/{entry['number']})"
    # Struck through when closed. A roadmap that shows finished work as pending is worse
    # than no roadmap.
    return label if entry["open"] else f"~~{label}~~ **done**"


def render(model: dict[str, object]) -> str:
    numbers = load_numbers()
    totals = model["totals"]  # type: ignore[index]
    crit = model["critical_path"]  # type: ignore[index]

    out: list[str] = [
        "# Lexpert — MVP Roadmap",
        "",
        "> Companion to [lexpert_plan.md](lexpert_plan.md) (why it is built this way) and",
        "> [lexpert_issues.md](lexpert_issues.md) (the full backlog). This document is the",
        "> **build order**: which phase comes when, what each one is finished enough to",
        "> demonstrate, and which issues set the floor on elapsed time.",
        ">",
        "> **This file is generated.** Edit `scripts/backlog/phases.py` for the phase structure",
        "> and checkpoints, or the issue data alongside it, then run",
        "> `python scripts/backlog/generate.py`. Do not edit this file by hand.",
        "",
        "## At a glance",
        "",
        "| | |",
        "| --- | --- |",
        f"| MVP issues | {totals['mvp_issues']} |",  # type: ignore[index]
        f"| Build track | {totals['mvp_build_issues']} issues, "  # type: ignore[index]
        f"{totals['mvp_build_days']} issue-days |",  # type: ignore[index]
        f"| Design track | {totals['mvp_design_issues']} issues, "  # type: ignore[index]
        f"{totals['mvp_design_days']} issue-days |",  # type: ignore[index]
        f"| Critical path | **{crit['days']} issue-days** across {crit['count']} issues |",  # type: ignore[index]
        f"| Beta issues | {totals['beta_issues']} ({totals['beta_days']} issue-days) |",  # type: ignore[index]
        "",
        "**Issue-days are effort, not calendar days** — they exclude review, rework, and the",
        "fact that one person works on one thing at a time. Sizes: S = half a day, M = 1-2",
        "days, L = 3 or more.",
        "",
        "**Two tracks run in parallel.** The design track is the designer's work, the build",
        "track is the implementer's, so the two figures do not add into a delivery date. What",
        "connects them is the dependency graph: no screen is implemented before its design",
        "exists, which is why the design track starts on day one rather than when the backend",
        "is ready.",
        "",
        "**The critical path is the number that matters for \"when could this be done\".** It is",
        "the longest dependency chain, so it is the floor on elapsed time however many people",
        "work — each link cannot start until the one before it lands. Slippage on the path moves",
        "the milestone; slippage elsewhere usually does not.",
        "",
    ]

    # --- start here, per track. Both people start on day one, on different issues.
    def first_unblocked(design: bool) -> dict[str, object] | None:
        for phase in model["phases"]:  # type: ignore[union-attr]
            for issue in phase["issues"]:  # type: ignore[union-attr]
                if ("design" in issue["labels"]) is design and not issue["depends"]:  # type: ignore[operator]
                    return issue
        return None

    build_first = first_unblocked(design=False)
    design_first = first_unblocked(design=True)

    out += ["## Start here", ""]
    out.append("Both tracks start on day one, on different issues.")
    out.append("")
    if build_first is not None:
        out += [
            f"**Build track** — {link(str(build_first['id']), numbers)} "
            f"{build_first['title']}. No dependencies, and every other engineering issue waits "
            "on it.",
            "",
            "  Then straight down the critical path: "
            + " -> ".join(f"`{i}`" for i in crit["chain"][:6])  # type: ignore[index]
            + " -> ...",
            "",
        ]
    if design_first is not None:
        out += [
            f"**Design track** — {link(str(design_first['id']), numbers)} "
            f"{design_first['title']}. Research before pixels; read "
            "[the design brief](../design/design_brief.md) first.",
            "",
        ]

    # --- phase table of contents
    out += [
        "## Phases",
        "",
        "| # | Phase | Issues | Effort | Checkpoint |",
        "| --- | --- | --- | --- | --- |",
    ]
    for phase in model["phases"]:  # type: ignore[union-attr]
        checkpoint = str(phase["checkpoint"]).split(". ")[0].rstrip(".")
        out.append(
            f"| {phase['number']} | [{phase['name']}](#{phase['number']}-"
            f"{str(phase['name']).lower().replace(' ', '-')}) "
            f"| {len(phase['issues'])} | {phase['days']}d | {checkpoint} |"  # type: ignore[arg-type]
        )
    out.append("")

    # --- each phase
    for phase in model["phases"]:  # type: ignore[union-attr]
        prefixes = ", ".join(f"`{p}`" for p in phase["prefixes"])  # type: ignore[union-attr]
        out += [
            "---",
            "",
            f"## {phase['number']}. {phase['name']}",
            "",
            f"*{len(phase['issues'])} issues &middot; {phase['days']} issue-days &middot; "  # type: ignore[arg-type]
            f"{prefixes}*",
            "",
            str(phase["what"]),
            "",
            f"> **Checkpoint.** {phase['checkpoint']}",
            "",
            "| Issue | Deliverable | After | Size |",
            "| --- | --- | --- | --- |",
        ]
        for issue in phase["issues"]:  # type: ignore[union-attr]
            marker = " **·**" if issue["critical"] else ""
            deps = ", ".join(f"`{d}`" for d in issue["depends"]) or "—"  # type: ignore[union-attr]
            out.append(
                f"| {link(str(issue['id']), numbers)}{marker} "
                f"| **{issue['title']}.** {issue['one_line']}. "
                f"| {deps} | {issue['size']} |"
            )
        out += [
            "",
            "Rows marked **·** are on the critical path.",
            "",
        ]

    # --- critical path
    out += [
        "---",
        "",
        "## The critical path",
        "",
        f"{crit['count']} of the {totals['mvp_issues']} MVP issues form the longest dependency "  # type: ignore[index]
        f"chain, at {crit['days']} issue-days:",  # type: ignore[index]
        "",
    ]
    for step, task_id in enumerate(crit["chain"], 1):  # type: ignore[union-attr]
        out.append(f"{step}. {link(str(task_id), numbers)}")
    out.append("")

    # --- early starts
    out += [
        "---",
        "",
        "## Issues that can start out of order",
        "",
        "Shallow dependencies, so these are safe to pull forward when something on the critical",
        "path is blocked, or if a second person joins.",
        "",
        "| Issue | Why it is safe early | After |",
        "| --- | --- | --- |",
    ]
    for entry in model["early_starts"]:  # type: ignore[union-attr]
        deps = ", ".join(f"`{d}`" for d in entry["depends"]) or "—"  # type: ignore[union-attr]
        out.append(f"| {link(str(entry['id']), numbers)} | {entry['why']} | {deps} |")
    out.append("")

    # --- decisions
    out += [
        "---",
        "",
        "## Decisions to settle before they cost anything",
        "",
    ]
    for decision in model["open_decisions"]:  # type: ignore[union-attr]
        out += [
            f"### {decision['title']} — {link(str(decision['id']), numbers)}",
            "",
            str(decision["detail"]),
            "",
        ]

    # --- beta
    out += [
        "---",
        "",
        "## Beta, after the MVP",
        "",
        f"{totals['beta_issues']} issues, {totals['beta_days']} issue-days, and the reason the "  # type: ignore[index]
        "`EscrowProvider` boundary exists.",
        "",
        "| Issue | Deliverable | Size |",
        "| --- | --- | --- |",
    ]
    for issue in model["beta"]:  # type: ignore[union-attr]
        out.append(
            f"| {link(str(issue['id']), numbers)} | **{issue['title']}.** "
            f"{issue['one_line']}. | {issue['size']} |"
        )
    out += [
        "",
        "Two Beta issues are gated on legal advice rather than on code, and neither should be",
        "started before it arrives: `BETA-01` on the payment and BCT memo, `BETA-03` on a",
        "confirmed compliant cross-border flow.",
        "",
        "---",
        "",
        "## Parallelisable waves",
        "",
        "A dependency levelling of the whole backlog: everything in a wave depends only on",
        "earlier waves, so a wave is what *can* run at once, not what must. Useful for deciding",
        "what a second person could pick up without waiting.",
        "",
        "| Wave | Issues |",
        "| --- | --- |",
    ]
    for entry in model["waves"]:  # type: ignore[union-attr]
        ids = ", ".join(f"`{i}`" for i in entry["ids"])  # type: ignore[union-attr]
        out.append(f"| {entry['wave']} | {ids} |")
    out.append("")

    return "\n".join(out)
