#!/usr/bin/env bash
# Bulk-create the Lexpert backlog as GitHub issues.
#
# GENERATED by scripts/backlog/generate.py - do not edit by hand.
#
# Idempotent by issue title: an existing title is skipped, so re-running after adding
# backlog entries creates only what is missing.
#
#   bash scripts/create_issues.sh
#   bash scripts/create_issues.sh --dry-run
set -euo pipefail

DRY_RUN="${1:-}"
cd "$(dirname "$0")/.."

if ! gh auth status >/dev/null 2>&1; then
  echo "gh is not authenticated. Run: gh auth login" >&2
  exit 1
fi

echo "Reading existing issue titles..."
EXISTING="$(gh issue list --state all --limit 400 --json title -q ".[].title")"

created=0
skipped=0

create() {
  local id="$1" title="$2" milestone="$3"; shift 3
  local full="$id $title"
  if grep -Fxq "$full" <<< "$EXISTING"; then
    echo "skip    $full"
    skipped=$((skipped + 1))
    return 0
  fi
  if [[ "$DRY_RUN" == "--dry-run" ]]; then
    echo "would   $full"
    return 0
  fi
  local label_args=()
  for label in "$@"; do label_args+=(--label "$label"); done
  gh issue create --title "$full" --milestone "$milestone" \
    --body-file ".github/issue-bodies/$(echo "$id" | tr "[:upper:]" "[:lower:]").md" \
    "${label_args[@]}"
  created=$((created + 1))
}


# --- FND: Foundation and infra ---
create "FND-01" "Monorepo scaffolding for apps/web and apps/api" "MVP" "infra"
create "FND-02" "API configuration and secrets handling" "MVP" "infra" "backend"
create "FND-03" "PostgreSQL, SQLAlchemy and Alembic baseline" "MVP" "database" "infra" "backend"
create "FND-04" "Activate the CI workflow and add required status checks to the ruleset" "MVP" "ci" "infra"
create "FND-05" "API application skeleton with module boundaries and error envelope" "MVP" "backend" "api" "infra"
create "FND-06" "Web app shell: routing, layout, French i18n catalogue and API client" "MVP" "frontend" "infra"
create "FND-07" "Domain reference data: verticals, professions, regulators and statuses" "MVP" "backend" "database" "good-first-issue"

# --- AUT: Identity and accounts ---
create "AUT-01" "User model, registration and JWT login for the three roles" "MVP" "auth" "backend" "database"
create "AUT-02" "Email and phone verification, and password reset" "MVP" "auth" "backend"
create "AUT-03" "Role-based access control and route guards" "MVP" "auth" "backend" "api"
create "AUT-04" "Web authentication flows and guarded routes" "MVP" "frontend" "auth"

# --- KYC: Professional verification (KYC-Pro) ---
create "KYC-01" "KYC-Pro data model and review state machine" "MVP" "kyc-pro" "database" "backend"
create "KYC-02" "Document upload with private storage" "MVP" "kyc-pro" "backend" "compliance"
create "KYC-03" "Per-vertical verification rule sets for CNOM, the Bar and the OECT" "MVP" "kyc-pro" "backend" "compliance"
create "KYC-04" "Verification submission and status API" "MVP" "kyc-pro" "api" "backend"
create "KYC-05" "Professional onboarding wizard" "MVP" "frontend" "kyc-pro"
create "KYC-06" "Admin verification review queue and decisions" "MVP" "admin" "kyc-pro" "backend"
create "KYC-07" "Admin verification review interface" "MVP" "frontend" "admin" "kyc-pro"

# --- PRO: Profiles and discovery ---
create "PRO-01" "Professional public profile model and hourly rate" "MVP" "backend" "database"
create "PRO-02" "Professional search and filtering API" "MVP" "api" "backend" "database"
create "PRO-03" "Professional profile management screens" "MVP" "frontend"
create "PRO-04" "Client search and professional profile pages" "MVP" "frontend"

# --- SCH: Scheduling ---
create "SCH-01" "Availability model: weekly rules, exceptions and buffers" "MVP" "scheduling" "backend" "database"
create "SCH-02" "Bookable slot computation" "MVP" "scheduling" "backend" "api"
create "SCH-03" "Professional availability management screens" "MVP" "frontend" "scheduling"
create "SCH-04" "Client booking calendar with timezone handling" "MVP" "frontend" "scheduling"

# --- ESC: Booking and simulated escrow ---
create "ESC-01" "EscrowProvider interface and the simulator adapter" "MVP" "escrow" "backend"
create "ESC-02" "Double-entry ledger with a balance invariant" "MVP" "escrow" "database" "backend"
create "ESC-03" "Consultation booking and the escrow state machine" "MVP" "escrow" "backend" "database"
create "ESC-04" "Immutable audit log for escrow transitions" "MVP" "escrow" "compliance" "database"
create "ESC-05" "Price computation: rate, duration and commission" "MVP" "escrow" "backend" "good-first-issue"
create "ESC-06" "Auto-release job for the one-hour hold window" "MVP" "escrow" "backend"
create "ESC-07" "Cancellation and no-show policy engine" "MVP" "escrow" "backend"
create "ESC-08" "Client checkout with the simulated payment step" "MVP" "frontend" "escrow"
create "ESC-09" "Professional earnings and consultation history views" "MVP" "frontend" "escrow"

# --- CON: Consultation sessions ---
create "CON-01" "Video provider adapter with room and token issuance" "MVP" "consultation" "backend"
create "CON-02" "Session lifecycle and the SESSION_ENDED signal into escrow" "MVP" "consultation" "escrow" "backend"
create "CON-03" "Consultation room interface with audio-only fallback" "MVP" "frontend" "consultation"
create "CON-04" "Consent capture and the no-recording policy" "MVP" "compliance" "consultation"

# --- DSP: Disputes, back-office and ratings ---
create "DSP-01" "Raising a dispute inside the hold window" "MVP" "escrow" "backend"
create "DSP-02" "Admin dispute mediation with release, refund and partial outcomes" "MVP" "admin" "escrow" "backend"
create "DSP-03" "Dispute screens for the client and the back-office" "MVP" "frontend" "admin"
create "DSP-04" "Ratings and reviews after release" "MVP" "backend" "frontend"

# --- NOT: Notifications ---
create "NOT-01" "Notification service with email and SMS adapters" "MVP" "backend"
create "NOT-02" "Lifecycle notifications for the whole consultation journey" "MVP" "backend"

# --- CMP: Compliance and hardening ---
create "CMP-01" "Privacy policy, data-processing register and data export" "MVP" "compliance" "backend" "docs"
create "CMP-02" "Sensitive-data logging guard" "MVP" "compliance" "backend"
create "CMP-03" "API documentation and contract tests" "MVP" "api" "docs" "test"

# --- BETA: Beta ---
create "BETA-01" "Integrate a licensed payment partner behind the EscrowProvider interface" "Beta" "escrow" "backend" "compliance"
create "BETA-02" "Local payment methods: D17, Flouci, Konnect and Paymee" "Beta" "escrow" "frontend" "backend"
create "BETA-03" "Diaspora payments and foreign-exchange constraints" "Beta" "escrow" "compliance" "backend"
create "BETA-04" "Professional subscription tiers and featured listings" "Beta" "backend" "frontend" "escrow"
create "BETA-05" "Data retention, deletion and the INPDP compliance package" "Beta" "compliance" "backend" "docs"
create "BETA-06" "Observability: structured logging, metrics, tracing and alerting" "Beta" "infra" "backend"
create "BETA-07" "Deployment pipeline, environments and secret management" "Beta" "infra" "ci"
create "BETA-08" "Raise the coverage gate and add load and resilience testing" "Beta" "ci" "test"
create "BETA-09" "Arabic localization alongside French" "Beta" "frontend"
create "BETA-10" "Pilot readiness: seeding, support tooling and the KPI dashboard" "Beta" "admin" "docs" "backend"

echo ""
echo "created: $created   skipped: $skipped"
if [[ "$DRY_RUN" != "--dry-run" ]]; then
  echo ""
  echo "Current backlog:"
  gh issue list --limit 400 --json number,title,milestone \
    -q '.[] | "\(.number)\t\(.milestone.title // "-")\t\(.title)"'
fi
