"""Reject a commit message that breaks the two non-negotiable repository rules.

`CLAUDE.md` rules 1 and 2 forbid AI attribution and emojis anywhere, including commit
messages. Those rules are worth exactly as much as their enforcement, so this runs at the
`commit-msg` stage alongside the conventional-commit check.

Usage (pre-commit passes the message file):

    python scripts/hooks/check_commit_message.py .git/COMMIT_EDITMSG
"""

from __future__ import annotations

import re
import sys
import unicodedata

# Substrings that indicate AI attribution, matched case-insensitively. Kept as plain
# substrings rather than one big regex so a failure can name the exact phrase found.
ATTRIBUTION_PHRASES = [
    "generated with",
    "generated by claude",
    "co-authored-by: claude",
    "co-authored-by: copilot",
    "co-authored-by: github copilot",
    "co-authored-by: cursor",
    "co-authored-by: devin",
    "co-authored-by: aider",
    "created with claude",
    "written by claude",
    "with the help of claude",
    "claude code",
    "🤖",
]

# Trailers that are legitimate: a real human co-author is fine.
ATTRIBUTION_ALLOWLIST_HINT = (
    "A human co-author trailer is fine. This rule targets AI attribution only."
)

MAX_SUBJECT_LENGTH = 72


def emoji_positions(text: str) -> list[tuple[int, str]]:
    """Return (index, character) for every emoji-like codepoint in `text`.

    Uses Unicode general categories plus the pictographic ranges rather than a hard-coded
    emoji list, so a new emoji is caught without updating this file. Symbols that appear
    legitimately in prose and code -- currency, mathematical operators, arrows -- are not
    treated as emoji.
    """
    found: list[tuple[int, str]] = []
    for index, char in enumerate(text):
        code = ord(char)
        if code < 0x2100:  # ASCII and Latin supplements: never emoji
            continue
        category = unicodedata.category(char)
        # So (symbol, other) covers the emoji blocks; Cs/Co are surrogates and private use.
        if category not in {"So", "Cs", "Co"}:
            continue
        # Allow a small set of non-emoji pictographic symbols that carry real meaning.
        if char in "™®©†‡‰":  # trademark, registered, etc.
            continue
        # Arrows and mathematical operators are not emoji.
        if 0x2190 <= code <= 0x22FF:
            continue
        found.append((index, char))
    return found


def check(message: str) -> list[str]:
    problems: list[str] = []

    # Ignore the comment block git appends to the editor buffer; it is not committed.
    body_lines = [line for line in message.splitlines() if not line.startswith("#")]
    committed = "\n".join(body_lines)
    stripped = committed.strip()

    if not stripped:
        return ["the commit message is empty"]

    # A merge, revert or fixup commit has a message git generates; do not police it.
    subject = body_lines[0] if body_lines else ""
    if subject.startswith(("Merge ", "Revert ", "fixup!", "squash!", "amend!")):
        return []

    lowered = committed.lower()
    for phrase in ATTRIBUTION_PHRASES:
        if phrase in lowered:
            problems.append(
                f"contains AI attribution: {phrase!r}. "
                "CLAUDE.md rule 1 forbids it -- describe the change only. "
                + ATTRIBUTION_ALLOWLIST_HINT
            )

    for index, char in emoji_positions(committed):
        name = unicodedata.name(char, "unnamed")
        problems.append(
            f"contains an emoji at position {index}: {char!r} ({name}). "
            "CLAUDE.md rule 2 forbids emojis anywhere."
        )
        break  # one report is enough; listing every emoji is noise

    if len(subject) > MAX_SUBJECT_LENGTH:
        problems.append(
            f"the subject line is {len(subject)} characters; keep it to "
            f"{MAX_SUBJECT_LENGTH} or fewer"
        )

    if subject.endswith("."):
        problems.append("the subject line ends with a full stop; drop it")

    # The conventional-commit hook validates the type prefix. This only catches the case it
    # cannot see: a subject that is a bare type with no description.
    if re.fullmatch(r"(feat|chore|docs|tests|bug|ci)(\([a-z]+\))?:\s*", subject):
        problems.append("the subject has a type but no description")

    return problems


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: check_commit_message.py <path-to-message-file>", file=sys.stderr)
        return 2

    path = sys.argv[1]
    try:
        with open(path, encoding="utf-8") as handle:
            message = handle.read()
    except OSError as exc:
        print(f"cannot read commit message file {path}: {exc}", file=sys.stderr)
        return 2

    problems = check(message)
    if not problems:
        return 0

    print("Commit message rejected:\n", file=sys.stderr)
    for problem in problems:
        print(f"  - {problem}", file=sys.stderr)
    print(
        "\nSee CLAUDE.md and CONTRIBUTING.md. Format: "
        "<type>(<scope>): <short imperative subject>",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
